### ISSUE TITLE
[Feature] get all toilet

### ISSUE THREAD

**Issue by darkmagic66** [Exceed-Group11/Mini-Project-Super-Toilet#2]
## API Document

GET `{{host_api}}/toilet/`

## API Response

```json
{
    "results": [
        {
            "toilet_id": 1,
            "status": true,
            "time_in": 16000000000
        }
   ]
}
```

definition

toilet_id -> หมายเลขห้อง
status -> true มีคนใช้
time_in -> เวลาคนเข้า

**Comment by sirateek** [comment]
This feature has been merged. Closing this now
